# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04ef58f34e177bac3754d97afb6abe33a85d076d7a2dad67bb38db373f1903bfe8550a9c2aaddab8a42685dce78cee3da627d720a660a0ba372c3f674882f447

test:
  secret_key_base: 0f46a30337e57819b895bd406286da9cfe2f56a27cc877332be501534d092243b572b768becb9f28f4eccf1fe6749aa9822ee3ae7b2273214464e1ea87b2243b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
